XmlSaxParserException: Fixed copy constructor and assignment operator to copy the line/column number.  Added overridden whatString() so that line number and column number are included.